"use client";

import { useState, useTransition } from "react";
import { createTemplateVersionAction } from "@/app/actions/release-foundations";

type Template = { id: string; society_id: string | null; template_key: string; name: string; category: string; version: number; status: string; subject_template: string | null; body_template: string; variables: string[]; output_format: string; updated_at: string };

export function TemplatesClient({ templates }: { templates: Template[] }) {
  const [editing, setEditing] = useState<Template | null>(null); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const input = "w-full rounded border border-[#333] bg-[#171717] px-3 py-2 text-sm text-text-primary";
  function submit(formData: FormData) { startTransition(async () => {
    const result = await createTemplateVersionAction({ templateKey: String(formData.get("templateKey")??""), name: String(formData.get("name")??""), category: String(formData.get("category")??"LETTER"), subject: String(formData.get("subject")??""), body: String(formData.get("body")??""), outputFormat: String(formData.get("outputFormat")??"DOCX") as "HTML"|"TEXT"|"PDF"|"DOCX"|"EMAIL", activate: formData.get("activate") === "on" });
    setMessage(result.success ? `Template version ${result.data.version} saved.` : result.error); if (result.success) setEditing(null);
  }); }
  return <div className="page-container"><div className="page-header"><div><h1 className="font-headline-lg-mobile text-headline-lg-mobile md:font-headline-lg md:text-headline-lg text-text-primary">Letter & Message Templates</h1><p className="mt-1 text-sm text-[#9CA3AF]">Versioned drafts—replace wording when approved formats arrive</p></div><button onClick={()=>setEditing({ id:"",society_id:null,template_key:"",name:"",category:"LETTER",version:0,status:"DRAFT",subject_template:"",body_template:"",variables:[],output_format:"DOCX",updated_at:"" })} className="rounded bg-[#10B981] px-4 py-2 text-sm font-medium text-white">New Template</button></div>
    {message && <p className="mb-4 rounded border border-[#333] bg-[#1c1b1b] px-4 py-3 text-sm text-[#D1D5DB]">{message}</p>}
    {editing && <form action={submit} className="queue-section mb-5 grid grid-cols-1 gap-4 p-5 md:grid-cols-2"><label className="text-sm text-[#9CA3AF]">Template key<input name="templateKey" required defaultValue={editing.template_key} className={`${input} mt-1`}/></label><label className="text-sm text-[#9CA3AF]">Name<input name="name" required defaultValue={editing.name} className={`${input} mt-1`}/></label><label className="text-sm text-[#9CA3AF]">Category<select name="category" defaultValue={editing.category} className={`${input} mt-1`}><option>LETTER</option><option>EMAIL</option><option>NOTICE</option><option>FORM</option></select></label><label className="text-sm text-[#9CA3AF]">Output<select name="outputFormat" defaultValue={editing.output_format} className={`${input} mt-1`}><option>DOCX</option><option>PDF</option><option>EMAIL</option><option>HTML</option><option>TEXT</option></select></label><label className="text-sm text-[#9CA3AF] md:col-span-2">Subject<input name="subject" defaultValue={editing.subject_template ?? ""} className={`${input} mt-1`}/></label><label className="text-sm text-[#9CA3AF] md:col-span-2">Body<textarea name="body" required rows={10} defaultValue={editing.body_template} className={`${input} mt-1 font-mono`}/><span className="mt-1 block text-xs text-[#6B7280]">Use variables such as {"{{member_name}}"}, {"{{unit_number}}"} and {"{{society_name}}"}.</span></label><label className="flex items-center gap-2 text-sm text-[#D1D5DB]"><input type="checkbox" name="activate"/> Activate this version</label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setEditing(null)} className="rounded border border-[#444] px-4 py-2 text-sm text-[#D1D5DB]">Cancel</button><button disabled={pending} className="rounded bg-[#10B981] px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{pending?"Saving...":"Save New Version"}</button></div></form>}
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">{templates.map((template)=><article key={template.id} className="queue-section p-5"><div className="flex justify-between gap-3"><div><p className="font-mono text-xs text-[#10B981]">{template.template_key} · v{template.version}</p><h2 className="mt-1 font-semibold text-text-primary">{template.name}</h2></div><span className="h-fit rounded border border-[#444] px-2 py-1 text-xs" style={{color:template.status==="ACTIVE"?"#10B981":"#9CA3AF"}}>{template.status}</span></div><p className="mt-3 line-clamp-4 whitespace-pre-wrap text-sm text-[#9CA3AF]">{template.body_template}</p><div className="mt-4 flex items-center justify-between"><p className="text-xs text-[#6B7280]">{template.society_id ? "Society version" : "Platform draft"} · {template.output_format}</p><button onClick={()=>setEditing(template)} className="rounded border border-[#444] px-3 py-1.5 text-xs text-[#D1D5DB]">Create society version</button></div></article>)}</div>
  </div>;
}
