"use client";
import{useTransition}from"react";
import{markAllNotificationsReadAction,markNotificationReadAction}from"@/app/actions/notifications";
type Notification={id:string;notification_type:string;title:string;message:string;entity_type:string|null;entity_id:string|null;action_url:string|null;read_at:string|null;created_at:string};
export function NotificationsClient({notifications}:{notifications:Notification[]}){
  const[pending,startTransition]=useTransition();const unread=notifications.filter(n=>!n.read_at).length;
  function mark(id:string){startTransition(async()=>{await markNotificationReadAction({notificationId:id});});}
  function markAll(){startTransition(async()=>{await markAllNotificationsReadAction();});}
  return <div className="page-container"><div className="page-header"><div><h1 className="text-3xl font-bold text-text-primary">Notifications</h1><p className="mt-1 text-sm text-[#9CA3AF]">{unread} unread · workflow actions, deadlines and updates</p></div>{unread>0&&<button disabled={pending} onClick={markAll} className="rounded border border-[#10B981] px-4 py-2 text-sm text-[#10B981]">Mark all read</button>}</div><section className="queue-section">{notifications.length===0?<p className="p-12 text-center text-sm text-[#6B7280]">No notifications yet.</p>:notifications.map(n=><article key={n.id} className="flex gap-3 border-b border-[#292929] px-5 py-4" style={{backgroundColor:n.read_at?"transparent":"rgba(16,185,129,.04)"}}><span className="material-symbols-outlined mt-0.5 text-[#10B981]">notifications</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><h2 className="text-sm font-medium text-text-primary">{n.title}</h2><time className="whitespace-nowrap text-xs text-[#6B7280]">{new Date(n.created_at).toLocaleString("en-IN")}</time></div><p className="mt-1 text-sm text-[#9CA3AF]">{n.message}</p><div className="mt-2 flex gap-3">{n.action_url&&<a href={n.action_url} onClick={()=>mark(n.id)} className="text-xs text-[#10B981] underline">Open</a>}{!n.read_at&&<button disabled={pending} onClick={()=>mark(n.id)} className="text-xs text-[#9CA3AF] underline">Mark read</button>}</div></div></article>)}</section></div>;
}
