"use server";
import {revalidatePath} from "next/cache";
import {getServerContext,nextSequenceNumber,wrapAction,type ActionResult} from "@/lib/context";
import {resolveUserContext,requirePermission} from "@/server/services/AccessService";
import {PERMISSIONS} from "@/types";
import {writeAuditCritical} from "@/lib/audit";
import {createAdminClient} from "@/lib/supabase/admin";

export interface NomineeInput{fullName:string;relationship?:string;dateOfBirth?:string;address?:string;phone?:string;email?:string;sharePercentage:number;isMinor?:boolean;guardianName?:string}
export async function createNominationAction(input:{memberId:string;unitId?:string;notes?:string;nominees:NomineeInput[]}):Promise<ActionResult<{id:string;nominationNumber:string}>>{
 return wrapAction(async()=>{const{supabase,societyId,wingId,userId}=await getServerContext();requirePermission(await resolveUserContext(societyId,wingId),PERMISSIONS.NOMINATION_MANAGE);
  if(input.nominees.length<1||input.nominees.length>10)throw new Error("Add between one and ten nominees.");const total=input.nominees.reduce((s,n)=>s+Number(n.sharePercentage),0);if(Math.abs(total-100)>0.001)throw new Error("Nominee shares must total exactly 100%.");
  for(const nominee of input.nominees){if(!nominee.fullName.trim())throw new Error("Every nominee needs a name.");if(nominee.isMinor&&!nominee.guardianName?.trim())throw new Error(`Guardian is required for minor nominee ${nominee.fullName}.`);}
  const nominationNumber=await nextSequenceNumber(supabase,societyId,"NOMINATION","NOM");const{data,error}=await supabase.from("nominations").insert({society_id:societyId,member_id:input.memberId,unit_id:input.unitId||null,nomination_number:nominationNumber,status:"SUBMITTED",notes:input.notes?.trim()||null,created_by:userId}).select("id").single();if(error)throw new Error(error.message);
  const{error:nomineesError}=await supabase.from("nominees").insert(input.nominees.map((n,index)=>({nomination_id:data.id,full_name:n.fullName.trim(),relationship:n.relationship?.trim()||null,date_of_birth:n.dateOfBirth||null,address:n.address?.trim()||null,phone:n.phone?.trim()||null,email:n.email?.trim()||null,share_percentage:Number(n.sharePercentage),is_minor:n.isMinor??false,guardian_name:n.guardianName?.trim()||null,sort_order:index})));
  if(nomineesError){await createAdminClient().from("nominations").delete().eq("id",data.id);throw new Error(nomineesError.message);}await writeAuditCritical({societyId,wingId,actorUserId:userId,action:"NOMINATION_SUBMITTED",entityType:"nomination",entityId:data.id,newValues:{nominationNumber,memberId:input.memberId,nomineeCount:input.nominees.length}});revalidatePath("/members/nominations");return{id:data.id,nominationNumber};});
}

export async function decideNominationAction(input:{id:string;decision:"APPROVED"|"REJECTED"|"CORRECTION_REQUIRED";comments?:string}):Promise<ActionResult>{return wrapAction(async()=>{const{supabase,societyId,wingId,userId}=await getServerContext();const context=await resolveUserContext(societyId,wingId);if(context.isPlatformAdmin||context.roleName!=="Society Admin"||context.wingId)throw new Error("A society-wide Society Admin must decide nominations.");requirePermission(context,PERMISSIONS.NOMINATION_MANAGE);const{data:old,error:readError}=await supabase.from("nominations").select("id,status,member_id").eq("id",input.id).eq("society_id",societyId).single();if(readError)throw new Error("Nomination not found.");const{error}=await supabase.from("nominations").update({status:input.decision,effective_from:input.decision==="APPROVED"?new Date().toISOString().slice(0,10):null,notes:input.comments?.trim()||null}).eq("id",input.id).eq("society_id",societyId);if(error)throw new Error(error.message);await writeAuditCritical({societyId,wingId,actorUserId:userId,action:"NOMINATION_DECIDED",entityType:"nomination",entityId:input.id,oldValues:{status:old.status},newValues:{status:input.decision,comments:input.comments??null}});revalidatePath("/members/nominations");});}

export async function createAssociateMembershipAction(input:{primaryMemberId:string;unitId?:string;applicantName:string;applicantEmail?:string;applicantPhone?:string;relationship?:string;consentReceived:boolean;entranceFeeAmount:number;feePaidAt?:string;notes?:string}):Promise<ActionResult<{id:string;applicationNumber:string}>>{return wrapAction(async()=>{const{supabase,societyId,wingId,userId}=await getServerContext();requirePermission(await resolveUserContext(societyId,wingId),PERMISSIONS.ASSOCIATE_MEMBER_MANAGE);if(!input.applicantName.trim())throw new Error("Applicant name is required.");if(!input.consentReceived)throw new Error("Primary-member consent is required.");if(input.entranceFeeAmount<0)throw new Error("Fee cannot be negative.");const applicationNumber=await nextSequenceNumber(supabase,societyId,"ASSOCIATE_MEMBERSHIP","ASC");const{data,error}=await supabase.from("associate_memberships").insert({society_id:societyId,primary_member_id:input.primaryMemberId,unit_id:input.unitId||null,application_number:applicationNumber,applicant_name:input.applicantName.trim(),applicant_email:input.applicantEmail?.trim()||null,applicant_phone:input.applicantPhone?.trim()||null,relationship:input.relationship?.trim()||null,consent_received:true,entrance_fee_amount:input.entranceFeeAmount,fee_paid_at:input.feePaidAt?new Date(input.feePaidAt).toISOString():null,status:"SUBMITTED",notes:input.notes?.trim()||null,created_by:userId}).select("id").single();if(error)throw new Error(error.message);await writeAuditCritical({societyId,wingId,actorUserId:userId,action:"ASSOCIATE_MEMBERSHIP_SUBMITTED",entityType:"associate_membership",entityId:data.id,newValues:{applicationNumber,primaryMemberId:input.primaryMemberId,applicantName:input.applicantName}});revalidatePath("/members/associates");return{id:data.id,applicationNumber};});}

export async function decideAssociateMembershipAction(input:{id:string;decision:"APPROVED"|"REJECTED"|"CORRECTION_REQUIRED";comments?:string}):Promise<ActionResult>{return wrapAction(async()=>{const{supabase,societyId,wingId,userId}=await getServerContext();const context=await resolveUserContext(societyId,wingId);if(context.isPlatformAdmin||context.roleName!=="Society Admin"||context.wingId)throw new Error("A society-wide Society Admin must decide associate memberships.");requirePermission(context,PERMISSIONS.ASSOCIATE_MEMBER_MANAGE);const{data:application,error:readError}=await supabase.from("associate_memberships").select("id,status,applicant_name,applicant_email,applicant_phone,unit_id,approved_member_id").eq("id",input.id).eq("society_id",societyId).single();if(readError)throw new Error("Associate application not found.");let approvedMemberId=application.approved_member_id;if(input.decision==="APPROVED"&&!approvedMemberId){const memberNumber=await nextSequenceNumber(supabase,societyId,"MEMBER","MBR");const{data:member,error:memberError}=await supabase.from("members").insert({society_id:societyId,unit_id:application.unit_id,member_number:memberNumber,full_name:application.applicant_name,email:application.applicant_email,phone:application.applicant_phone,member_type:"ASSOCIATE",status:"ACTIVE",effective_from:new Date().toISOString().slice(0,10),created_by:userId}).select("id").single();if(memberError)throw new Error(memberError.message);approvedMemberId=member.id;}const{error}=await supabase.from("associate_memberships").update({status:input.decision,approved_member_id:approvedMemberId,notes:input.comments?.trim()||null}).eq("id",input.id).eq("society_id",societyId);if(error)throw new Error(error.message);await writeAuditCritical({societyId,wingId,actorUserId:userId,action:"ASSOCIATE_MEMBERSHIP_DECIDED",entityType:"associate_membership",entityId:input.id,oldValues:{status:application.status},newValues:{status:input.decision,approvedMemberId}});revalidatePath("/members/associates");revalidatePath("/members");});}
