"use server";
import {getServerContext,wrapAction,type ActionResult} from "@/lib/context";
import {resolveUserContext,requirePermission} from "@/server/services/AccessService";
import {PERMISSIONS} from "@/types";
import {writeAuditCritical} from "@/lib/audit";
import {revalidatePath} from "next/cache";

export async function uploadVendorDocumentAction(input:{vendorId:string;documentType:string;title:string;documentNumber?:string;issuedOn?:string;expiresOn?:string;storagePath:string;fileName:string;mimeType:string;fileSize:number;checksumSha256?:string;replacesDocumentId?:string}):Promise<ActionResult<{id:string}>>{
 return wrapAction(async()=>{const{supabase,societyId,wingId,userId}=await getServerContext();const context=await resolveUserContext(societyId,wingId);if(!context.isPlatformAdmin&&!context.permissions.has(PERMISSIONS.VENDOR_UPDATE)&&!context.permissions.has(PERMISSIONS.VENDOR_PORTAL))throw new Error("You do not have permission to upload vendor documents.");if(!input.storagePath.startsWith(`${societyId}/vendors/${input.vendorId}/`))throw new Error("Invalid vendor document path.");if(!input.title.trim()||!input.documentType.trim())throw new Error("Document type and title are required.");let version=1;let replaced:{id:string;version:number}|null=null;if(input.replacesDocumentId){const{data,error}=await supabase.from("vendor_documents").select("id,version").eq("id",input.replacesDocumentId).eq("vendor_id",input.vendorId).eq("society_id",societyId).single();if(error||!data)throw new Error("Document version to replace was not found.");replaced=data;version=data.version+1;}const{data,error}=await supabase.from("vendor_documents").insert({society_id:societyId,vendor_id:input.vendorId,document_type:input.documentType.trim().toUpperCase(),title:input.title.trim(),document_number:input.documentNumber?.trim()||null,issued_on:input.issuedOn||null,expires_on:input.expiresOn||null,storage_path:input.storagePath,file_name:input.fileName,mime_type:input.mimeType,file_size_bytes:input.fileSize,status:"UPLOADED",version,replaces_document_id:replaced?.id??null,uploaded_by:userId,metadata:{checksum_sha256:input.checksumSha256??null}}).select("id").single();if(error)throw new Error(error.message);if(replaced){const{error:replaceError}=await supabase.from("vendor_documents").update({status:"REPLACED"}).eq("id",replaced.id);if(replaceError)throw new Error(replaceError.message);}await writeAuditCritical({societyId,wingId,actorUserId:userId,action:replaced?"VENDOR_DOCUMENT_REPLACED":"VENDOR_DOCUMENT_UPLOADED",entityType:"vendor_document",entityId:data.id,newValues:{vendorId:input.vendorId,documentType:input.documentType,version,expiresOn:input.expiresOn??null,replacesDocumentId:replaced?.id??null}});revalidatePath(`/vendors/${input.vendorId}`);revalidatePath("/vendor");return{id:data.id};});
}

export async function reviewVendorDocumentAction(input:{documentId:string;decision:"VERIFIED"|"REJECTED";reason?:string}):Promise<ActionResult>{return wrapAction(async()=>{const{supabase,societyId,wingId,userId}=await getServerContext();const context=await resolveUserContext(societyId,wingId);if(context.isPlatformAdmin||context.roleName!=="Society Admin"||context.wingId)throw new Error("A society-wide Society Admin must review vendor documents.");requirePermission(context,PERMISSIONS.VENDOR_VERIFY);if(input.decision==="REJECTED"&&!input.reason?.trim())throw new Error("A rejection reason is required.");const{data,error}=await supabase.from("vendor_documents").update({status:input.decision,verified_by:input.decision==="VERIFIED"?userId:null,verified_at:input.decision==="VERIFIED"?new Date().toISOString():null,rejection_reason:input.decision==="REJECTED"?input.reason?.trim()??null:null}).eq("id",input.documentId).eq("society_id",societyId).select("vendor_id").single();if(error)throw new Error(error.message);await writeAuditCritical({societyId,wingId,actorUserId:userId,action:input.decision==="VERIFIED"?"VENDOR_DOCUMENT_VERIFIED":"VENDOR_DOCUMENT_REJECTED",entityType:"vendor_document",entityId:input.documentId,newValues:{status:input.decision,reason:input.reason??null}});revalidatePath(`/vendors/${data.vendor_id}`);revalidatePath("/vendor");});}
